import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

interface PackageJson {
  name: string;
  version: string;
}

const scriptDir = dirname(fileURLToPath(import.meta.url));
const packageRoot = resolve(scriptDir, "..");
const packageJson = JSON.parse(
  await readFile(resolve(packageRoot, "package.json"), "utf8"),
) as PackageJson;

const source = `// Generated by scripts/generate-package-metadata.mts. Do not edit by hand.
export const PACKAGE_NAME = ${JSON.stringify(packageJson.name)};
export const PACKAGE_VERSION = ${JSON.stringify(packageJson.version)};
`;

await writeFile(resolve(packageRoot, "src/genui-lib/packageMetadata.ts"), source, "utf8");
