root = VLayout([performanceCard])
performanceCard = Card([cardHeader, performanceMetrics], "card", "standard")
cardHeader = CardHeader("Q1 Performance")
performanceMetrics = Descriptions([revenueField, profitField, growthField, customersField], null, null, 2)
revenueField = DescField("Revenue", "$2.45M")
profitField = DescField("Profit", "$890K")
growthField = DescField("QoQ Growth", "12.3%")
customersField = DescField("New Customers", "1,247")