root = VLayout([performanceCard])
performanceCard = Card([cardHeader, cardBody], "card", "standard")
cardHeader = CardHeader("Q1 Performance")
cardBody = Descriptions([revenueField, profitField, growthField], null, null, 2)
revenueField = DescField("Revenue", "$1.2M")
profitField = DescField("Profit", "$350K")
growthField = DescField("Growth", "+15%")