root = VLayout([latencyCard])
latencyCard = Card([cardTitle, sparkline, lastValue], "card", "standard")
cardTitle = Text("Latency Trend", "large")
sparkline = MiniChart("line", data.sparkline)
lastValue = Text("Last: " + @FormatNumber(@Last(data.sparkline), 2) + " ms")