root = VLayout([title, breakdownTable])
title = Text("Regional Sales Breakdown", "large")
breakdownTable = Table([regionCol, revenueCol, updatedCol], data.report.breakdown)
regionCol = Col("Region", "region")
revenueCol = Col("Revenue", "revenue", {cell: @Render("v", Text("$" + @FormatNumber(v, 0)))})
updatedCol = Col("Last Updated", "updatedAt", {cell: @Render("v", Text(@FormatDate(v, "date")))})