root = Stack([employeeTable])
employeeTable = Table([nameCol, salaryCol, joinedCol, statusCol], data.employees)
nameCol = Col("Name", "name", {cell: @Render("v", "row", Link("http://localhost:5173/" + row.name, v))})
salaryCol = Col("Salary", "salary", {cell: @Render("v", TextContent(@FormatNumber(v, 0)))})
joinedCol = Col("Joined", "joinedAt", {cell: @Render("v", TextContent(@FormatDate(v, "date")))})
statusCol = Col("Status", "active", {cell: @Render("v", "row", @Switch(v, {"1": Tag("Active", "success"), "0": Tag("Inactive", "danger")}, Tag("Unknown", "neutral")))})