root = VLayout([employeeTable])
employeeTable = Table([nameCol, salaryCol, joinedCol], data.employees)
nameCol = Col("Name", "name")
salaryCol = Col("Salary", "salary", {sortable: true})
joinedCol = Col("Joined", "joinedAt", {cell: @Render("v", Text(@FormatDate(v, "date")))})