root = Stack([employeeTable])
employeeTable = Table([nameCol, salaryCol, joinedCol, statusCol], data.employees)
nameCol = Col("Name", "name", {tooltip: true, cell: @Render("v", "row", Link("http://localhost:5173/" + row.name, v))})
salaryCol = Col("Salary", "salary", {cell: @Render("v", Text("$" + @FormatNumber(v, 0)))})
joinedCol = Col("Joined", "joinedAt", {cell: @Render("v", Text(@FormatDate(v, "date")))})
statusCol = Col("Status", "active", {cell: @Render("v", v ? Tag("Active", "success") : Tag("Inactive", "danger"))})