root = Stack([employeeTable])
employeeTable = Table([nameCol, salaryCol, joinedCol], data.employees)
nameCol = Col("Name", "name")
salaryCol = Col("Salary", "salary", {sortable: true, cell: @Render("v", TextContent(@FormatNumber(v, 0, "en-US") + " USD"))})
joinedCol = Col("Joined", "joinedAt", {sortable: true, cell: @Render("v", TextContent(@FormatDate(v, "date")))})