root = Stack([deviceTable])
deviceTable = Table([nameCol, statusCol, interfacesCol], data.devices, {expandRow: @Render("v", deviceDetailCard)})
nameCol = Col("Device Name", "name")
statusCol = Col("Status", "status", {cell: @Render("v", Tag(v, v == "Up" ? "success" : "danger"))})
interfacesCol = Col("Interfaces", "interfaces", {cell: @Render("v", TextContent(@Count(v) + " interfaces"))})
deviceDetailCard = Card([header, interfaceList], "sunk", "full")
header = CardHeader(@Render("v", "row", "Device: " + row.name), @Render("v", "row", "Status: " + row.status))
interfaceList = List(@Each(row.interfaces, "iface", interfaceItemTemplate))
interfaceItemTemplate = Item(@Render("v", "row", TextContent(iface.name + " - " + iface.speed)))