root = Stack([portTitle, portsTable])
portTitle = Text("端口列表", "large")
portsTable = Table([nameCol, statusCol, trendCol], data.ports)
nameCol = Col("端口名称", "name", {tooltip: true})
statusCol = Col("状态", "status", {cell: @Render("v", Tag(v == "Up" ? "Up" : "Down", v == "Up" ? "success" : "danger"))})
trendCol = Col("速率趋势", "trend", {cell: @Render("v", MiniChart("line", v))})