root = VLayout([header, portsTable])
header = Text("端口列表", "large")
portsTable = Table([nameCol, statusCol, trendCol], data.ports)
nameCol = Col("端口名称", "name")
statusCol = Col("状态", "status", {cell: @Render("v", Tag(v, @Switch(v, {"Up": "success", "Down": "danger"}, "neutral")))})
trendCol = Col("速率趋势", "trend", {cell: @Render("v", MiniChart("line", v))})