root = VLayout([employeeTable])
employeeTable = Table([nameCol, salaryCol, joinedCol], data.employees)
nameCol = Col("Name", "name", {tooltip: true})
salaryCol = Col("Salary", "salary", {sortable: true})
joinedCol = Col("Joined", "joinedAt", {cell: @Render("v", "row", Text(@FormatDate(row.joinedAt, "date")))})