root = VLayout([pageTitle, mainTabs])
pageTitle = Text("System Dashboard", "large")
mainTabs = Tabs([overviewTab, settingsTab], {})
overviewTab = {value: "overview", label: "Overview", content: [overviewCard]}
overviewCard = Card([VLayout([desc, statusTag], "m")], "card", "standard")
desc = Descriptions([DescField("Version", "v2.4.1"), DescField("Uptime", "14d 6h 32m"), DescField("License", "Enterprise")], "System Overview", null, 2)
statusTag = Tag("All Systems Operational", "success", "check_circle", "md")
settingsTab = {value: "settings", label: "Settings", content: [settingsForm]}
settingsForm = Form([nameField, emailField, themeField], "vertical", "left", {name: "Admin", email: "admin@example.com", theme: "light"})
nameField = {label: "Display Name", name: "name", rules: [{required: true}], component: Text("")}
emailField = {label: "Email", name: "email", rules: [{required: true}], component: Text("")}
themeField = {label: "Theme", name: "theme", component: Text("")}